version: '3.8'

services:
  bank-api:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    container_name: bank-api
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BankDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - JwtSettings__SecretKey=YourSuperSecretKeyForJWTTokenGeneration123456789
      - Jw