<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Bank.Notifications.Application\Bank.Notifications.Application.csproj" />
    <ProjectReference Include="..\Bank.Notifications.Domain\Bank.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Bank.BuildingBlocks.Application\Bank.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\Bank.Contracts\Bank.Contracts.csproj" />
  </ItemGroup>
</Project>
